### ISSUE TITLE
Dask Q08 Fails at the shuffle stage

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/gpu-bdb#144] opened 2020-12-04 22:34 UTC
We may have a failure with dask Q08 (reported by @pentschev ) .  Will look into triaging this soon.
 
```python

$ python tpcx_bb_query_08.py --config_file=../../benchmark_runner/benchmark_config.yaml
```
```python
Using default arguments
{
  "type": "Scheduler",
  "id": "Scheduler-48c46fbc-5f68-4ee2-abf9-cafc9a2047e8",
  "address": "tcp://10.33.227.163:8786",
  "services": {
    "dashboard": 8787
  },
  "workers": {}
}
Connected!
Encountered Exception while running query
```python
Traceback (most recent call last):
  File "/datasets/pentschev/miniconda3/envs/rapids-tpcx-bb/lib/python3.7/site-packages/xbb_tools/utils.py", line 280, in run_dask_cudf_query
    config=config,
  File "/datasets/pentschev/miniconda3/envs/rapids-tpcx-bb/lib/python3.7/site-packages/xbb_tools/utils.py", line 61, in benchmark
    result = func(*args, **kwargs)
  File "tpcx_bb_query_08.py", line 272, in main
    merged_df = merged_df.shuffle(on=["wcs_user_sk"])
  File "/datasets/pentschev/miniconda3/envs/rapids-tpcx-bb/lib/python3.7/site-packages/dask_cudf/core.py", line 339, in shuffle
    return super().shuffle(*args, shuffle="tasks", **kwargs)
  File "/datasets/pentschev/miniconda3/envs/rapids-tpcx-bb/lib/python3.7/site-packages/dask/dataframe/core.py", line 1242, in shuffle
    compute=compute,
  File "/datasets/pentschev/miniconda3/envs/rapids-tpcx-bb/lib/python3.7/site-packages/dask/dataframe/shuffle.py", line 289, in shuffle
    compute=compute,
  File "/datasets/pentschev/miniconda3/envs/rapids-tpcx-bb/lib/python3.7/site-packages/dask/dataframe/shuffle.py", line 352, in rearrange_by_column
    df, col, max_branch, npartitions, ignore_index=ignore_index
  File "/datasets/pentschev/miniconda3/envs/rapids-tpcx-bb/lib/python3.7/site-packages/dask/dataframe/shuffle.py", line 594, in rearrange_by_column_tasks
    stages = int(math.ceil(math.log(n) / math.log(max_branch)))
ValueError: math domain error
```

**Comment by beckernick** [comment] 2020-12-04 22:50
Must be brand new. This worked in yesterday's nightlies with dask 2.30 and distributed 2.31. Shouldnt be too hard to bisect and find it

**Comment by beckernick** [comment] 2020-12-07 18:26
@pentschev I wasn't able to reproduce this on a DGX-2 with TCP or NVLink in today's environment of 0.17 nightlies and dask 2.30 distributed 2.30.1

Closing for now, but please reopen if this error surfaces again.

**Closed by beckernick** 2020-12-07 18:26 UTC

**Comment by pentschev** [comment] 2020-12-08 21:41
It turns out I was not on the latest commit of this repo, with the newest one everything works. Sorry for the noise here.
